Tweaking main scripts
TinyCircuits/TinyCircuits-Thumby-Code-Editor pull request #42
Opened 2022-12-13 23:31 UTC by ace-dent

The `main.py` and `menu.py` should be lean.
Small tweaks to clean things up. Hopefully all safe - but please scrutinise use of `lightsleep` in the exception handling (untested).

2022-12-14 00:11 UTC, fuglaro commented on ThumbyGames/main.py
> +reset()
I think this line is inaccessible anyway.

2022-12-14 00:11 UTC, fuglaro commented on ThumbyGames/menu.py
> +machine.reset()
Just like this line is inaccessible. Unless I'm missing something?

2022-12-14 00:14 UTC, fuglaro commented on ThumbyGames/main.py
> +        lightsleep(1000)
My personal thoughts are that I don't think this code path is saving much by using lightsleep. I think using lightsleep implies intention for this code path to be energy optimised. I wouldn't say that is that important... For me this is complexity that is giving misleading intention.

2022-12-14 00:15 UTC, fuglaro commented on ThumbyGames/menu.py
> +thumby.display.setFPS(50)
Won't this make the splash screen animate slower?

2022-12-14 00:18 UTC, fuglaro commented on ThumbyGames/menu.py
> +#print(gc.mem_free())
I don't love commented code, but there are other examples. But besides this, leaving these lines in could potentially save meaningful power consumption if the menu loop is left going for a long time, because then there will be less for the garbage collector to do each time it does a pass. Not sure if that is why this was left here though.

2022-12-14 01:47 UTC, ace-dent commented on ThumbyGames/menu.py
> +#print(gc.mem_free())
Thanks for the feedback. I've reinstated gc at this point.

2022-12-14 10:28 UTC, fuglaro commented on ThumbyGames/menu.py
> +thumby.display.setFPS(50)
Cool.

2022-12-14 10:29 UTC, fuglaro commented on ThumbyGames/main.py
> +        lightsleep(1000)
Debatable for sure.

2022-12-14 11:43 UTC, ace-dent commented on ThumbyGames/main.py
> +        lightsleep(1000)
Agreed. Have reverted. Thank you.

2022-12-14 21:49 UTC, fuglaro commented on ThumbyGames/menu.py
> +files = listdir("/Games")
Can I get you to add something else that is going to seem a bit strange? The emulator flavour of this being monkey patched here: https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/blob/master/js/play.js#L247

An alternative to this is maintaining two variants of menu.py, one for the emulator.

2022-12-14 21:49 UTC, fuglaro commented on ThumbyGames/menu.py
> -    if(os.stat("/Games/"+files[k])[0] != 16384):
Also here: https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/blob/master/js/play.js#L250

2022-12-14 21:56 UTC, ace-dent commented on ThumbyGames/main.py
> +freq(133_000_000)
Games will be launched from menu.py, where we set to 48 MHz.
Plus games should be designed around fps not cpu clock speed!... ;-)

2022-12-14 22:16 UTC, fuglaro commented on ThumbyGames/main.py
> +freq(133_000_000)
Oh yeah! You are right!!! My bad. What is this code path anyway? This must be Fast Execute mode. All good then!

2022-12-17 00:51 UTC, fuglaro commented
Looking awesome. I love these changes. I can do some more testing of the newer stuff tomorrow.

2022-12-21 14:16 UTC, fuglaro commented
Note for testing:
I think only three games on the Arcade currently use the thumby saves API:
AstroJumper
BurnsCharade
PicoPac

2022-12-21 22:20 UTC, fuglaro commented on ThumbyGames/main.py
> +if(IDPin.value() == 0):
Is this right? This makes my SPI Thumby attempt to load I2C and end up having a black screen.
Pin values for my Thumby is:
```
15=1
14=0
13=1
12=1
```

2022-12-21 22:21 UTC, fuglaro commented on js/play.js
>              'machine.mem32[SCRATCH0_ADDR]=1',
As discussed off thread, my suggested changes will go into a separate PR later.

2022-12-22 13:54 UTC, fuglaro commented on ThumbyGames/menu.py
> +thumby.display.setFPS(50)
Can you check how it looks to you when you turn on the Thumby while it is USB connected and ready to auto-connect to the IDE? I'd be keen to get your opinion on the before and after for that case.

2022-12-22 14:01 UTC, fuglaro commented on ThumbyGames/menu.py
> +thumby.display.setFPS(50)
Can you check how it looks to you when you turn on the Thumby while it is USB connected and ready to auto-connect to the IDE? How it works for me looks like it glitches, even though it doesn't. Because now the Code Editor screen shows at a weird point in the animation. I'd be keen to get your opinion on the before and after for that case. Also, since all this does change the visual animation behaviour of the most prominent part of the startup, could you flag this in the PR description? So TC don't miss this change? And its easier to track when that changes in the history?

2022-12-23 11:53 UTC, ace-dent commented on ThumbyGames/menu.py
> +    mem32[0x4005800C]=1 # Watchdog timer scratch register
After discussion, have decided to keep the pre-calculated hex address. Personally I find this clearer. With the comment line, it should be enough for any curious mind to lookup the RP2040 data sheet and understand. I also doubt any User would casually tinkering with this!

2022-12-23 11:55 UTC, ace-dent commented on js/play.js
>              'machine.mem32[SCRATCH0_ADDR]=1',
As agreed, @fuglaro has developed a *real* fix that will be in a separate PR.
I have now committed a minimal fix for this PR.

2022-12-23 11:59 UTC, ace-dent commented on ThumbyGames/main.py
> +if(IDPin.value() == 0):
Thanks @fuglaro for your investigative work.
Committed the fix: it scans the first two ID pins to determine the HWID. This works for the current PCB revisions, `0`–`3` and a future `4`. For extended HWID revisions, further pins may need to be scanned. Ideally we could just import the HWID section of `thumbyHardware` to reduce code duplication.

2022-12-23 12:33 UTC, ace-dent commented on ThumbyGames/menu.py
> +thumby.display.setFPS(50)
Thanks. Following discussion and testing, have restored the shorter scrolling time by increasing the pixel step from y+1, to y+2. Fixed in recent commit.

2023-01-09 16:21 UTC, masonova1 requested changes
Can we keep the WDT scratch address as a named constant? It's unclear to me how this improves readability, and this code only needs to run once on-startup, so lookup overhead shouldn't be a problem here. Other than that, everything looks good!

2023-01-09 17:06 UTC, ace-dent commented
@masonova1 - 
Thanks for taking the time to review this PR (and many commits!)...
Readability is perhaps subjective. May I ask you: Is there a need to communicate to the casual user, that the base address is at` 0x40058000` and the first register '0' is at `0x0C`? I kinda think that's great for a data sheet, but practically, I want to just glance at this 'magic' address where we set and read a flag ...IMH). I also think with using the next 3 registers, it starts to look cluttered. (See [here](http://forum.tinycircuits.com/index.php?topic=2517.0) and [here](https://github.com/ace-dent/TinyCircuits-Thumby-Code-Editor/blob/c3576ac4332a0f4e9dc069d13f6630fd79e236bf/ThumbyGames/main.py#L33-L79)). If you feel strongly on this, I can add back in the extra variables. Many thanks, 
Andrew

2023-01-09 17:14 UTC, masonova1 commented
> @masonova1 - Thanks for taking the time to review this PR (and many commits!)... Readability is perhaps subjective. May I ask you: Is there a need to communicate to the casual user, that the base address is at `0x40058000` and the first register '0' is at `0x0C`? I kinda think that's great for a data sheet, but practically, I want to just glance at this 'magic' address where we set and read a flag ...IMHO. I also think with using the next 3 registers, it starts to look cluttered. (See [here](http://forum.tinycircuits.com/index.php?topic=2517.0) and [here](https://github.com/ace-dent/TinyCircuits-Thumby-Code-Editor/blob/c3576ac4332a0f4e9dc069d13f6630fd79e236bf/ThumbyGames/main.py#L33-L79)). If you feel strongly on this, I can add back in the extra variables. Many thanks, Andrew

I'm honestly fine with less words. If somebody wants the exposition, they would need to go back to the definition to see what it means anyways. If somebody complains, we'll bring it back. We'll get this merged soon.

2023-01-09 17:16 UTC, merged